def create_report(
    analysis,
    risks,
    recommendations
):
    """
    Report Agent

    Collects outputs from all specialized AI agents
    and generates the final business intelligence report.
    """

    return f"""
# 📊 OpsPilot AI - Enterprise Business Intelligence Report

---

## 🤖 Multi-Agent Execution Summary

| Agent | Status |
|-------|--------|
| Analyst Agent | ✅ Completed |
| Risk Agent | ✅ Completed |
| Recommendation Agent | ✅ Completed |
| Report Agent | ✅ Generated Final Report |

---

# 📈 Executive Analysis

{analysis}

---

# ⚠️ Risk Assessment

{risks}

---

# 🚀 Strategic Recommendations & KPI Plan

{recommendations}

---

# ✅ Final Business Summary

This report was generated through the collaborative execution of multiple specialized AI agents.

Each agent performed an independent responsibility:

- **Analyst Agent** → Business analysis & root causes
- **Risk Agent** → Risk identification & impact assessment
- **Recommendation Agent** → Strategic recommendations & KPIs
- **Report Agent** → Aggregated all outputs into a unified executive report

---

Generated by **OpsPilot AI Enterprise Multi-Agent Business Intelligence Platform**
"""