def create_report(
    analysis,
    risks,
    recommendations
):
    return f"""
# OPSPILOT AI BUSINESS REPORT

## Executive Analysis
{analysis}

---

## Risk Assessment
{risks}

---

## Recommendations & KPI Plan
{recommendations}

---

Generated by OpsPilot Multi-Agent System
"""