import React from "react";

const CombinedReport = ({ outputs }) => {
  if (!outputs || outputs.length === 0) {
    return null;
  }

  return (
    <div
      style={{
        marginTop: "30px",
        background: "rgba(255,255,255,0.05)",
        border: "1px solid rgba(255,255,255,0.08)",
        borderRadius: "18px",
        padding: "24px",
        color: "#fff",
      }}
    >
      <h2
        style={{
          marginBottom: "20px",
          fontSize: "26px",
          fontWeight: "700",
        }}
      >
        📋 Combined AI Report
      </h2>

      {outputs.map((agent, index) => (
        <div
          key={index}
          style={{
            marginBottom: "20px",
            padding: "18px",
            borderRadius: "12px",
            background: "rgba(255,255,255,0.04)",
          }}
        >
          <h3
            style={{
              color: "#38bdf8",
              marginBottom: "10px",
            }}
          >
            🤖 {agent.name}
          </h3>

          <p
            style={{
              whiteSpace: "pre-wrap",
              lineHeight: "1.7",
              color: "#d4d4d8",
            }}
          >
            {agent.output}
          </p>
        </div>
      ))}

      <div
        style={{
          marginTop: "25px",
          paddingTop: "20px",
          borderTop: "1px solid rgba(255,255,255,.08)",
        }}
      >
        <h3
          style={{
            color: "#22c55e",
            marginBottom: "10px",
          }}
        >
          ✅ Executive Summary
        </h3>

        <p
          style={{
            color: "#d4d4d8",
            lineHeight: "1.8",
          }}
        >
          This report combines insights generated by multiple AI agents.
          Together they analyze the business problem from operational,
          financial, strategic, customer, and risk perspectives to help
          decision-makers take informed actions.
        </p>
      </div>
    </div>
  );
};

export default CombinedReport;