export function generateReport(outputs = []) {
  if (!outputs.length) {
    return "No report available.";
  }

  let report = "OpsPilot AI Business Analysis Report\n\n";

  outputs.forEach((item, index) => {
    report += `=============================\n`;
    report += `Agent ${index + 1}: ${item.name}\n`;
    report += `=============================\n`;
    report += `${item.output}\n\n`;
  });

  report += "----------------------------------\n";
  report += "Generated by OpsPilot AI\n";

  return report;
}